// Rasterises the Natural Earth land outline (world-atlas) into a character
// grid: one string per row, "1" for land. Run once; the result is committed
// as src/lib/world-grid.ts, so the build needs none of these dev packages.
import { readFileSync, writeFileSync } from "node:fs"
import { geoContains, geoEquirectangular } from "d3-geo"
import { feature } from "topojson-client"

const topo = JSON.parse(readFileSync("node_modules/world-atlas/land-110m.json", "utf8"))
const land = feature(topo, topo.objects.land)
const COLS = 132
const ROWS = 46
const rows = []
for (let y = 0; y < ROWS; y++) {
  let row = ""
  for (let x = 0; x < COLS; x++) {
    const lon = (x / (COLS - 1)) * 360 - 180
    const lat = 80 - (y / (ROWS - 1)) * 140
    row += geoContains(land, [lon, lat]) ? "1" : "0"
  }
  rows.push(row)
}
writeFileSync(
  "src/lib/world-grid.ts",
  `/** Land mask, ${COLS}×${ROWS}, lon −180…180 by lat 80…−60. Generated by scripts/world-grid.mjs. */\nexport const WORLD_GRID: string[] = ${JSON.stringify(rows, null, 2)}\n`,
)
console.log(rows.join("\n"))
