/** Every frame on the page. Photography from Pexels (https://www.pexels.com) — `by` is the photographer. */
export type Frame = { id: number; n: number; name: string; place: string; category: Category; edit: Edit; by: string; alt: string }
export type Category = "Residential" | "Interior" | "Concrete" | "Facade" | "Civic" | "Stair"
export type Edit = "Relight" | "Sky" | "Season" | "Grade"

export const FRAMES: Frame[] = [
  {id: 17158806,n: 1,name: "Casa Lomas",place: "Lisbon, PT",category: "Facade",edit: "Relight",by: "Arthur  Swiffen",alt: "Close-up of a modern architectural facade featuring geometric patterns and textures."},
  {id: 39102530,n: 2,name: "Hall Brae",place: "Seville, ES",category: "Residential",edit: "Grade",by: "Ivanna Lebediuk",alt: "Elegant Mediterranean-style villas with terracotta roofs by the sea."},
  {id: 38073198,n: 3,name: "Casa Corbel",place: "Lisbon, PT",category: "Stair",edit: "Relight",by: "Karolina",alt: "Crossing metal staircases on an industrial building facade."},
  {id: 15422346,n: 4,name: "Maison Cairn",place: "Marfa, US",category: "Residential",edit: "Sky",by: "Dextar Studio ™",alt: "Contemporary house facade with geometric design elements and landscaping."},
  {id: 38246112,n: 5,name: "Atelier Soler",place: "Montreal, CA",category: "Interior",edit: "Season",by: "BI ravencrow",alt: "A spacious, empty industrial-style interior with modern design elements and natural lighting."},
  {id: 17947890,n: 6,name: "Court Heron",place: "Oaxaca, MX",category: "Interior",edit: "Grade",by: "Kirti  Phadke",alt: "Elegant living room with stylish furniture, marble stairs, and modern decor."},
  {id: 4933643,n: 7,name: "Tower Tilia",place: "Hobart, AU",category: "Residential",edit: "Relight",by: "Deepak DK",alt: "A modern suburban home at dusk, beautifully lit with exterior lights."},
  {id: 13678505,n: 8,name: "Annex Umber",place: "Cape Town, ZA",category: "Concrete",edit: "Sky",by: "Yena Kwon",alt: "Striking modern urban architecture with unique geometric structures and cityscape."},
  {id: 11831530,n: 9,name: "Haus Halden",place: "Aarhus, DK",category: "Concrete",edit: "Season",by: "Juan Diego",alt: "Close-up of a concrete Brutalist building showcasing geometric modern architecture."},
  {id: 12903905,n: 10,name: "Pavilion Norte",place: "Tbilisi, GE",category: "Facade",edit: "Grade",by: "Jan van der Wolf",alt: "Contemporary architectural facade with windows against a vibrant blue sky and clouds."},
  {id: 30165027,n: 11,name: "Haus Esker",place: "Aarhus, DK",category: "Residential",edit: "Season",by: "Keegan Checks",alt: "Charming white villas with outdoor seating, surrounded by vibrant greenery."},
  {id: 20418705,n: 12,name: "Pavilion Pell",place: "Tbilisi, GE",category: "Stair",edit: "Grade",by: "Wolfgang Weiser",alt: "Abstract view of a triangular staircase with blue hues."},
  {id: 19689322,n: 13,name: "Terrace Palisade",place: "Basel, CH",category: "Civic",edit: "Relight",by: "Israyosoy S.",alt: "Spacious and contemporary interior of the Soumaya Museum."},
  {id: 13771880,n: 14,name: "Block Alba",place: "Porto, PT",category: "Residential",edit: "Sky",by: "David Underland",alt: "Low-angle view of a modern building."},
  {id: 13705213,n: 15,name: "Wing Lomas",place: "Ghent, BE",category: "Interior",edit: "Season",by: "Adrien Olichon",alt: "A dark, minimalist hallway interior with intriguing lighting and textured walls."},
  {id: 29561705,n: 16,name: "Villa Yarrow",place: "Sintra, PT",category: "Residential",edit: "Grade",by: "Selim Karadayı",alt: "Modern suburban houses with stone accents under a twilight sky."},
  {id: 31024672,n: 17,name: "Studio Ashgrove",place: "Kyoto, JP",category: "Concrete",edit: "Relight",by: "Sarah  Rücker",alt: "Dramatic black and white photo of modern building facade with repetitive geometric design."},
  {id: 17594273,n: 18,name: "House Olmo",place: "Ljubljana, SI",category: "Facade",edit: "Season",by: "Thắng-Nhật Trần",alt: "Contemporary building facade featuring sharp geometric patterns in a modern architectural design."},
  {id: 30196347,n: 19,name: "Loft Heron",place: "Bergen, NO",category: "Residential",edit: "Sky",by: "Manish Jangid",alt: "Beautiful Mediterranean villa surrounded by lush forest and landscaped garden."},
  {id: 25368145,n: 20,name: "House Tilia",place: "Ljubljana, SI",category: "Stair",edit: "Season",by: "Luis Ribeiro",alt: "Artistic black and white shot of a spiral staircase."},
  {id: 19450764,n: 21,name: "Hall Umber",place: "Valparaíso, CL",category: "Civic",edit: "Grade",by: "Frazz Khalid",alt: "Contemporary museum building with circular design, striking cultural architecture."},
  {id: 12359215,n: 22,name: "Casa Halden",place: "Mérida, MX",category: "Residential",edit: "Relight",by: "Abdullah Asad",alt: "A modern residential building surrounded by greenery under a clear blue sky."},
  {id: 2191622,n: 23,name: "Maison Norte",place: "Tallinn, EE",category: "Interior",edit: "Sky",by: "David Yu",alt: "Explore the abstract beauty of minimalist concrete structures captured in striking black and white."},
  {id: 30386991,n: 24,name: "Atelier Calder",place: "Rotterdam, NL",category: "Interior",edit: "Season",by: "Huy Phan",alt: "Stylish living room featuring a navy sofa, indoor plants, and contemporary decor."},
  {id: 11673912,n: 25,name: "Court Merrow",place: "Seville, ES",category: "Concrete",edit: "Grade",by: "Mathias Reding",alt: "Close-up view of a contemporary building facade with unique geometric designs and windows."},
  {id: 2793444,n: 26,name: "Tower Linden",place: "Lisbon, PT",category: "Concrete",edit: "Relight",by: "Rick Han",alt: "Striking modern architecture of Geisel Library with unique facade design and bold structure."},
  {id: 11540260,n: 27,name: "Annex Tamar",place: "Marfa, US",category: "Facade",edit: "Sky",by: "Brian Phetmeuangmay",alt: "Stylish modern architecture at Getty Center."},
  {id: 9326059,n: 28,name: "Tower Lomas",place: "Lisbon, PT",category: "Residential",edit: "Relight",by: "Ahmet Polat",alt: "Elegant waterfront villas surrounded by lush greenery, ideal for a modern vacation retreat."},
  {id: 19394434,n: 29,name: "Annex Yarrow",place: "Marfa, US",category: "Stair",edit: "Sky",by: "Mihai Vlasceanu",alt: "Vertical shot of a modern metal staircase on a residential building."},
  {id: 11742925,n: 30,name: "Haus Ashgrove",place: "Montreal, CA",category: "Civic",edit: "Season",by: "Damian",alt: "Explore the unique modern architecture of the copper facade museum in Żory, Poland."},
  {id: 30580640,n: 31,name: "Pavilion Fenn",place: "Oaxaca, MX",category: "Residential",edit: "Grade",by: "Karolina K",alt: "Front view of twin modern houses with a symmetrical architectural design under a cloudy sky."},
  {id: 22862961,n: 32,name: "Terrace Olmo",place: "Hobart, AU",category: "Interior",edit: "Relight",by: "Francisco Miguel Santos",alt: "A unique architectural perspective showing a stairwell leading to an open skylight against a cloudy sky."},
  {id: 34117279,n: 33,name: "Block Fold",place: "Cape Town, ZA",category: "Interior",edit: "Sky",by: "Pınar Demir",alt: "Stylish wooden wall shelf with decor items in a modern living room."},
  {id: 22814896,n: 34,name: "Wing Rowan",place: "Aarhus, DK",category: "Residential",edit: "Season",by: "Stteven97",alt: "Apartment building with balconies silhouetted against a pink sunset sky, creating an urban evening scene."},
  {id: 17729218,n: 35,name: "Villa Marl",place: "Tbilisi, GE",category: "Concrete",edit: "Grade",by: "Costa Karabelas",alt: "Close-up view of a contemporary building with geometric patterns and concrete facade."},
  {id: 4328661,n: 36,name: "Studio Moraine",place: "Basel, CH",category: "Concrete",edit: "Relight",by: "Steve Pancrate",alt: "Concrete Brutalist building facade."},
  {id: 10298352,n: 37,name: "Loft Ardea",place: "Porto, PT",category: "Facade",edit: "Sky",by: "Gustavo Vizart",alt: "Close-up of a modern building facade featuring geometric glass panels and steel structure."},
  {id: 8681218,n: 38,name: "Studio Calder",place: "Basel, CH",category: "Residential",edit: "Relight",by: "Ksu&Eli Studio",alt: "Elegant villa surrounded by tropical plants, offering a serene vacation atmosphere."},
  {id: 16812645,n: 39,name: "Loft Merrow",place: "Porto, PT",category: "Stair",edit: "Sky",by: "Agit Akbulut",alt: "A contemporary building facade with staircases in an overcast urban setting of Beyoğlu, İstanbul."},
  {id: 37776339,n: 40,name: "House Linden",place: "Ghent, BE",category: "Residential",edit: "Season",by: "Dzmitry Charnou",alt: "Contemporary row houses with distinctive metal design reflecting on a serene river."},
  {id: 15465914,n: 41,name: "Hall Tamar",place: "Sintra, PT",category: "Interior",edit: "Grade",by: "Zhengdong Hu",alt: "Contemporary building interior featuring cubic light and sleek wall design."},
  {id: 34688219,n: 42,name: "Casa Isle",place: "Kyoto, JP",category: "Interior",edit: "Relight",by: "Moussa Idrissi",alt: "Spacious modern living room with elegant sofas and stylish decor."},
  {id: 18214902,n: 43,name: "Maison Verso",place: "Bergen, NO",category: "Residential",edit: "Sky",by: "David Brown",alt: "Vertical shot of a lit-up modern residential building façade at dusk."},
  {id: 38539691,n: 44,name: "Atelier Juno",place: "Ljubljana, SI",category: "Concrete",edit: "Season",by: "Raoul Turmond",alt: "Concrete staircase and modern building exterior under clear blue sky."},
  {id: 20111365,n: 45,name: "Court Oriel",place: "Valparaíso, CL",category: "Concrete",edit: "Grade",by: "Samuel Jerónimo",alt: "Vertical shot of brutalist building facade and traffic light."},
  {id: 9612453,n: 46,name: "Tower Vale",place: "Mérida, MX",category: "Facade",edit: "Relight",by: "Wika Wawrzeniecka",alt: "Contemporary building facade showcasing sleek geometric patterns in urban setting."},
  {id: 36394720,n: 47,name: "Court Fold",place: "Valparaíso, CL",category: "Residential",edit: "Grade",by: "Jonathan Borba",alt: "Stylish modern villas with wooden accents and thatched roofing by a pool under a vibrant sky."},
  {id: 15581384,n: 48,name: "Tower Rowan",place: "Mérida, MX",category: "Stair",edit: "Relight",by: "Jakob Jin",alt: "Sleek and modern architectural interior featuring a futuristic curved staircase with minimalist design."},
  {id: 34793765,n: 49,name: "Annex Marl",place: "Tallinn, EE",category: "Civic",edit: "Sky",by: "Natalya Rostun",alt: "Monochrome view of modern architectural design."},
  {id: 23639035,n: 50,name: "Haus Moraine",place: "Rotterdam, NL",category: "Residential",edit: "Season",by: "Brett Sayles",alt: "Minimalist building facade."},
  {id: 37763125,n: 51,name: "Pavilion Ardea",place: "Seville, ES",category: "Interior",edit: "Grade",by: "Devansh Rajput",alt: "Explore the smooth curves of a minimalist staircase in modern architecture."},
  {id: 20418771,n: 52,name: "Terrace Zenith",place: "Lisbon, PT",category: "Interior",edit: "Relight",by: "Sandeep Lasar",alt: "A lavish modern living area featuring chandeliers, luxurious seating, and elegant decor."},
  {id: 5800419,n: 53,name: "Block Delft",place: "Marfa, US",category: "Concrete",edit: "Sky",by: "Drew Anderson",alt: "Minimalist black and white photo of a modern building exterior showcasing geometric architectural elements."},
  {id: 31888836,n: 54,name: "Wing Loma Alta",place: "Montreal, CA",category: "Concrete",edit: "Season",by: "Gaby Lopez",alt: "Stunning view of a Brutalist building."},
  {id: 26547201,n: 55,name: "Villa Quinta",place: "Oaxaca, MX",category: "Facade",edit: "Grade",by: "Sydney Sang",alt: "Abstract view of an urban office building's repetitive window patterns, capturing modern architecture."},
  {id: 740587,n: 56,name: "Wing Isle",place: "Montreal, CA",category: "Residential",edit: "Season",by: "Min An",alt: "Contemporary hillside villas surrounded by lush greenery under an expansive sky."},
  {id: 19164602,n: 57,name: "Villa Verso",place: "Oaxaca, MX",category: "Stair",edit: "Grade",by: "Wolfgang Weiser",alt: "Captivating upward view of a spiral staircase inside the Sprinkenhof building."},
  {id: 33024243,n: 58,name: "Studio Juno",place: "Hobart, AU",category: "Civic",edit: "Relight",by: "Faheem Jackson",alt: "A grand staircase with elegant columns inside a renowned art museum."},
  {id: 16631149,n: 59,name: "Loft Oriel",place: "Cape Town, ZA",category: "Residential",edit: "Sky",by: "Axel Sandoval",alt: "Modern white building exterior with large windows and minimalist design in an urban setting."},
  {id: 5278940,n: 60,name: "House Vale",place: "Aarhus, DK",category: "Interior",edit: "Season",by: "𝗛&𝗖𝗢 　",alt: "Abstract view of a modern minimalist interior with geometric lines and subtle shadows."},
  {id: 38975400,n: 61,name: "Hall Dune",place: "Tbilisi, GE",category: "Interior",edit: "Grade",by: "McFollis",alt: "Sleek modern interior featuring a black accent wall, piano corner, and minimalist lighting."},
  {id: 9473066,n: 62,name: "Casa Ostra",place: "Basel, CH",category: "Concrete",edit: "Relight",by: "David Yu",alt: "A modern concrete building facade with repetitive windows creating a minimalistic architectural pattern."},
  {id: 4015825,n: 63,name: "Maison Orla",place: "Porto, PT",category: "Concrete",edit: "Sky",by: "Serinus",alt: "Close-up view of a brutalist concrete building facade showcasing geometric design and pattern."},
  {id: 15673574,n: 64,name: "Atelier Ribe",place: "Ghent, BE",category: "Facade",edit: "Season",by: "Efe Kuyu",alt: "Striking modern facade with geometric patterns."},
  {id: 20159461,n: 65,name: "Maison Ardea",place: "Porto, PT",category: "Residential",edit: "Sky",by: "Jakub Pabis",alt: "Contemporary white villas with solar panels."},
  {id: 15466789,n: 66,name: "Atelier Zenith",place: "Ghent, BE",category: "Stair",edit: "Season",by: "Ulrick Trappschuh",alt: "Modern residential building with a distinct spiral staircase and colorful facades."},
  {id: 16827933,n: 67,name: "Court Delft",place: "Sintra, PT",category: "Stair",edit: "Grade",by: "Mehmet Turgut  Kirkgoz",alt: "Geometric perspective of a modern spiral staircase with black handrails in a white interior."},
  {id: 8380592,n: 68,name: "Tower Loma Alta",place: "Kyoto, JP",category: "Residential",edit: "Relight",by: "Tony Mrst",alt: "Low angle shot of a peach-colored apartment building with balconies under a clear sky."},
  {id: 15009841,n: 69,name: "Annex Quinta",place: "Bergen, NO",category: "Interior",edit: "Sky",by: "Hakan Sevim",alt: "An atmospheric interior view of Sancaklar Mosque."},
  {id: 5793547,n: 70,name: "Haus Gable",place: "Ljubljana, SI",category: "Interior",edit: "Season",by: "Mariette de Villiers",alt: "Bright and airy modern living room with stylish furniture and natural light."},
  {id: 3882638,n: 71,name: "Terrace Tessel",place: "Mérida, MX",category: "Concrete",edit: "Relight",by: "d_odd_y",alt: "A striking view of a modern concrete structure against a vibrant blue sky."},
  {id: 20213634,n: 72,name: "Block Kestrel",place: "Tallinn, EE",category: "Concrete",edit: "Sky",by: "Can K",alt: "Striking brutalist facade of a building."},
  {id: 37582309,n: 73,name: "Wing Brisa",place: "Rotterdam, NL",category: "Facade",edit: "Season",by: "Tayssir Kadamany",alt: "Unique modern building facade featuring intricate lattice patterns under a clear sky."},
  {id: 16573669,n: 74,name: "Block Dune",place: "Tallinn, EE",category: "Residential",edit: "Sky",by: "Eyecon Design",alt: "A stunning modern villa showcasing luxury and elegance with exotic cars and lush greenery."},
  {id: 15404875,n: 75,name: "Wing Ostra",place: "Rotterdam, NL",category: "Stair",edit: "Season",by: "Ulrick Trappschuh",alt: "Contemporary residential buildings with spiral staircases bathed in warm sunlight."},
  {id: 3789026,n: 76,name: "Villa Orla",place: "Seville, ES",category: "Civic",edit: "Grade",by: "Abdullah Ghatasheh",alt: "Explore the captivating architecture of the National Museum of Qatar."},
  {id: 32666364,n: 77,name: "Studio Ribe",place: "Lisbon, PT",category: "Residential",edit: "Relight",by: "Mr RightGames",alt: "Contemporary urban home facade with circular cutouts and stone siding, offering a unique architectural style."},
  {id: 8357326,n: 78,name: "Loft Jetty",place: "Marfa, US",category: "Interior",edit: "Sky",by: "Marina M",alt: "Sleek minimalist interior with blue neon lights and white bar chairs."},
  {id: 33033173,n: 79,name: "House Wren",place: "Montreal, CA",category: "Residential",edit: "Season",by: "Zeze",alt: "Modern colorful townhouses in a Mediterranean setting during twilight."},
  {id: 3559252,n: 80,name: "Hall Weald",place: "Oaxaca, MX",category: "Concrete",edit: "Grade",by: "𝗛&𝗖𝗢 　",alt: "Abstract view of a modern architectural design featuring concrete pillars and dramatic shadows."},
  {id: 19328726,n: 81,name: "Maison Ceres",place: "Cape Town, ZA",category: "Facade",edit: "Sky",by: "Willian Justen de Vasconcellos",alt: "Close-up of a futuristic building facade glowing at twilight, highlighting intricate patterns and modern design."},
  {id: 37305866,n: 82,name: "Casa Gable",place: "Hobart, AU",category: "Residential",edit: "Relight",by: "Сокіл Sokil",alt: "Charming Mediterranean villas with lush palm trees and gardens under a bright blue sky."},
  {id: 5328953,n: 83,name: "Maison Saltmarsh",place: "Cape Town, ZA",category: "Stair",edit: "Sky",by: "Kien Tran",alt: "Captivating view of a spiral staircase illuminated at night with warm lighting, creating an abstract visual."},
  {id: 34551993,n: 84,name: "Atelier Tessel",place: "Aarhus, DK",category: "Civic",edit: "Season",by: "Nico C",alt: "Close-up of the Guggenheim Museum's architecture."},
  {id: 18078684,n: 85,name: "Court Kestrel",place: "Tbilisi, GE",category: "Residential",edit: "Grade",by: "Cemrecan Yurtman",alt: "Modern house exterior featuring balconies and a vibrant facade."},
  {id: 33685861,n: 86,name: "Tower Brisa",place: "Basel, CH",category: "Interior",edit: "Relight",by: "Essentia Media",alt: "Luxurious modern interior featuring marble floors and wood paneling for a sleek design."},
  {id: 29012619,n: 87,name: "Annex Brae",place: "Porto, PT",category: "Interior",edit: "Sky",by: "Beyza Kılıçdere",alt: "A minimalist living room with soft white sofas and large curtains, creating a cozy atmosphere."},
  {id: 2747599,n: 88,name: "Haus Corbel",place: "Ghent, BE",category: "Concrete",edit: "Season",by: "Bruno Thethe",alt: "A striking image showcasing minimalist concrete architecture with sharp geometric lines."},
  {id: 15285869,n: 89,name: "Pavilion Cairn",place: "Sintra, PT",category: "Concrete",edit: "Grade",by: "Nairod Reyes",alt: "Low-angle view of a brutalist building featuring a distinct circular design against a clear sky."},
  {id: 20956839,n: 90,name: "Terrace Soler",place: "Kyoto, JP",category: "Facade",edit: "Relight",by: "Mohammad Husaini",alt: "Black and white photo of a modern building facade."},
  {id: 5223143,n: 91,name: "Pavilion Jetty",place: "Sintra, PT",category: "Residential",edit: "Grade",by: "John Zook",alt: "A stunning Mediterranean style house with arched windows and terracotta tiles."},
  {id: 11012837,n: 92,name: "Terrace Wren",place: "Kyoto, JP",category: "Stair",edit: "Relight",by: "Fatma Nur  Anılır",alt: "Dramatic high-angle view of a spiral wooden staircase with metal handrails."},
  {id: 31907873,n: 93,name: "Block Weald",place: "Bergen, NO",category: "Civic",edit: "Sky",by: "Oli Liao",alt: "Explore the spiraling architecture inside a modern museum with visitors."},
  {id: 19344325,n: 94,name: "Wing Sable",place: "Ljubljana, SI",category: "Residential",edit: "Season",by: "Mido Makasardi ©️",alt: "Elegant modern house exterior with large windows under clear blue sky."},
  {id: 30699851,n: 95,name: "Villa Ceres",place: "Valparaíso, CL",category: "Interior",edit: "Grade",by: "Alexey K.",alt: "Stylish modern interior featuring a sleek curved staircase and minimalist design."},
  {id: 276746,n: 96,name: "Studio Esker",place: "Mérida, MX",category: "Interior",edit: "Relight",by: "Pixabay",alt: "Bright living room with elegant furniture and modern decor, perfect for relaxation."},
  {id: 19216762,n: 97,name: "Loft Pell",place: "Tallinn, EE",category: "Concrete",edit: "Sky",by: "Alex Quezada",alt: "A detailed view of modern concrete architecture featuring geometric angles and sharp lines."},
  {id: 7245554,n: 98,name: "House Palisade",place: "Rotterdam, NL",category: "Concrete",edit: "Season",by: "Olga Lioncat",alt: "A close-up view of a modern brutalist tower featuring rectangular windows and concrete textures."},
  {id: 39814972,n: 99,name: "Hall Alba",place: "Seville, ES",category: "Facade",edit: "Grade",by: "Alex Ivanov",alt: "Unique urban architecture showcasing geometric facades and modern design elements."},
]
